/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.SalesController;
import controller.TicketController;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Sales;

/**
 *
 * @author Douglas
 */
public class Cadastro extends javax.swing.JFrame {

    
    DefaultListModel salesModel;
    TicketController TK = new TicketController ();
    SalesController SC = new SalesController();
    
    public Cadastro() {
        ListSales();
        initComponents();
        initModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolBar = new javax.swing.JPanel();
        ToolBarTitle = new javax.swing.JLabel();
        ToolBarIcon = new javax.swing.JLabel();
        PainelItens = new javax.swing.JPanel();
        Itens = new javax.swing.JScrollPane();
        ListaItemCadastro = new javax.swing.JList<>();
        PainelMenu = new javax.swing.JPanel();
        ButtonCadastrar = new javax.swing.JButton();
        ButtonExlcuir = new javax.swing.JButton();
        ButtonFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextValor = new javax.swing.JTextField();
        ButtonVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 550));

        ToolBar.setBackground(new java.awt.Color(255, 255, 255));
        ToolBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        ToolBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ToolBarTitle.setText("CAIXA ABERTO");

        ToolBarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONE.png"))); // NOI18N
        ToolBarIcon.setText(" ");

        javax.swing.GroupLayout ToolBarLayout = new javax.swing.GroupLayout(ToolBar);
        ToolBar.setLayout(ToolBarLayout);
        ToolBarLayout.setHorizontalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(ToolBarIcon)
                .addContainerGap())
        );
        ToolBarLayout.setVerticalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ToolBarIcon)
                    .addComponent(ToolBarTitle))
                .addContainerGap())
        );

        PainelItens.setBackground(new java.awt.Color(255, 255, 255));

        ListaItemCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ListaItemCadastro.setToolTipText("");
        Itens.setViewportView(ListaItemCadastro);

        javax.swing.GroupLayout PainelItensLayout = new javax.swing.GroupLayout(PainelItens);
        PainelItens.setLayout(PainelItensLayout);
        PainelItensLayout.setHorizontalGroup(
            PainelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelItensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Itens)
                .addContainerGap())
        );
        PainelItensLayout.setVerticalGroup(
            PainelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelItensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Itens)
                .addContainerGap())
        );

        PainelMenu.setBackground(new java.awt.Color(255, 255, 255));

        ButtonCadastrar.setBackground(new java.awt.Color(0, 153, 0));
        ButtonCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCadastrar.setText("CADASTRAR");
        ButtonCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCadastrarMouseClicked(evt);
            }
        });

        ButtonExlcuir.setBackground(new java.awt.Color(255, 0, 51));
        ButtonExlcuir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonExlcuir.setForeground(new java.awt.Color(255, 255, 255));
        ButtonExlcuir.setText("EXLCUIR");
        ButtonExlcuir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonExlcuirMouseClicked(evt);
            }
        });

        ButtonFechar.setBackground(new java.awt.Color(51, 51, 255));
        ButtonFechar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonFechar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonFechar.setText("FECHAR");
        ButtonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonFecharMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("VALOR DA VENDA");

        TextValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TextValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextValorKeyPressed(evt);
            }
        });

        ButtonVer.setBackground(new java.awt.Color(102, 102, 102));
        ButtonVer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonVer.setForeground(new java.awt.Color(255, 255, 255));
        ButtonVer.setText("VER TOTAL");
        ButtonVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonVerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelMenuLayout = new javax.swing.GroupLayout(PainelMenu);
        PainelMenu.setLayout(PainelMenuLayout);
        PainelMenuLayout.setHorizontalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelMenuLayout.createSequentialGroup()
                        .addGroup(PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(ButtonExlcuir, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(ButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addGroup(PainelMenuLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1))
                            .addComponent(TextValor))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ButtonVer, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelMenuLayout.setVerticalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextValor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonExlcuir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(ButtonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void TextValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextValorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER && !"".equals(TextValor.getText())){
            Float valor = Float.valueOf(TextValor.getText().replaceAll(",", "."));
            Sales venda = new Sales();
            
            venda.setValorVenda(valor);         
            SC.save(venda);
            
                try {
                      TK.update();
                  } catch (SQLException ex) {
                      Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                  }finally{
                    loadSales();
                    TextValor.setText(" ");
                    TextValor.requestFocus();
                }
        }
    }//GEN-LAST:event_TextValorKeyPressed

    private void ButtonExlcuirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExlcuirMouseClicked
        // TODO add your handling code here:
        Verificacao vf = new Verificacao();
        vf.setVisible(true);
    }//GEN-LAST:event_ButtonExlcuirMouseClicked

    private void ButtonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonFecharMouseClicked
        try {
            // TODO add your handling code here:
            JOptionPane.showMessageDialog(null,"Total:" + TK.totalVenda());
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_ButtonFecharMouseClicked

    private void ButtonCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCadastrarMouseClicked
        // TODO add your handling code here:
            Float valor = Float.valueOf(TextValor.getText().replaceAll(",", "."));
            Sales venda = new Sales();
            venda.setValorVenda(valor);         
            SC.save(venda);
                try {
                      TK.update();
                  } catch (SQLException ex) {
                      Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                  }finally{
                    loadSales();
                    TextValor.setText(" ");
                    TextValor.requestFocus();
        }
    }//GEN-LAST:event_ButtonCadastrarMouseClicked

    private void ButtonVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVerMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            JOptionPane.showMessageDialog(null,"Total:" + TK.totalVenda());
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonVerMouseClicked

    public void ListSales(){
        SC = new SalesController();
    }
    
    public void initModel(){
        salesModel = new DefaultListModel();
        loadSales();
    }
           
    public void loadSales(){
        List<Sales> listSales = SC.getAll();
        salesModel.clear();
        for(int i = 0; i < listSales.size(); i++){
            Sales sale = listSales.get(i);
            salesModel.add(i, sale);
        }
        ListaItemCadastro.setModel(salesModel);
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonExlcuir;
    private javax.swing.JButton ButtonFechar;
    private javax.swing.JButton ButtonVer;
    private javax.swing.JScrollPane Itens;
    private javax.swing.JList<String> ListaItemCadastro;
    private javax.swing.JPanel PainelItens;
    private javax.swing.JPanel PainelMenu;
    private javax.swing.JTextField TextValor;
    private javax.swing.JPanel ToolBar;
    private javax.swing.JLabel ToolBarIcon;
    private javax.swing.JLabel ToolBarTitle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
