/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TicketController;
import javax.swing.JOptionPane;
import model.Ticket;

/**
 *
 * @author Douglas
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        MenuCaixa = new javax.swing.JMenu();
        MenuHistorico = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuBar.setBorder(null);
        MenuBar.setAlignmentX(1.0F);
        MenuBar.setAlignmentY(1.0F);
        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuBarMousePressed(evt);
            }
        });

        MenuCaixa.setText("Caixa");
        MenuCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCaixaMouseClicked(evt);
            }
        });
        MenuBar.add(MenuCaixa);

        MenuHistorico.setText("Histórico");
        MenuHistorico.setBorderPainted(false);
        MenuHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuHistorico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHistoricoMouseClicked(evt);
            }
        });
        MenuBar.add(MenuHistorico);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuBarMousePressed

    private void MenuCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCaixaMouseClicked
        // TODO add your handling code here:
        Ticket ticket = new Ticket();
        TicketController tk = new TicketController();
        ticket.setValorTotal(0.0f);
        tk.save(ticket);
        
        Cadastro caixa = new Cadastro();
        caixa.setExtendedState(TelaInicial.MAXIMIZED_BOTH);
        caixa.setVisible(true);
    }//GEN-LAST:event_MenuCaixaMouseClicked

    private void MenuHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHistoricoMouseClicked
        // TODO add your handling code here:
        Historico hs = new Historico();
        hs.setVisible(true);
    }//GEN-LAST:event_MenuHistoricoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuCaixa;
    private javax.swing.JMenu MenuHistorico;
    // End of variables declaration//GEN-END:variables
}
